In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings("ignore")

In [2]:
df=sns.load_dataset("iris")

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df["species"].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x=df.drop("species",axis=1)
y=df["species"]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [10]:
model_knn=KNeighborsClassifier(n_neighbors=13)

In [11]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [12]:
model_knn.score(X_test,y_test)

1.0

In [13]:
from sklearn.svm import SVC

In [14]:
model_svm=SVC(C= 10,kernel="linear",gamma="auto")

In [15]:
model_svm.fit(X_train,y_train)

SVC(C=10, gamma='auto', kernel='linear')

In [16]:
model_svm.score( X_test,y_test)

1.0

In [25]:
#lets use the grid search cv with svm model

In [26]:
from sklearn.model_selection import GridSearchCV

In [27]:
classifier= GridSearchCV((model_svm),{
    "C":[1,10,20,30],
    "kernel":["rbf","linear"],
  },cv=5,return_train_score=False)

In [28]:
classifier.fit(x,y)

GridSearchCV(cv=5, estimator=SVC(C=10, gamma='auto', kernel='linear'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [29]:
print(classifier.cv_results_)

{'mean_fit_time': array([0.00986967, 0.00998139, 0.00212402, 0.00536838, 0.00686321,
       0.00534759, 0.00367069, 0.00600972]), 'std_fit_time': array([0.00303048, 0.004546  , 0.00179042, 0.00040879, 0.00412861,
       0.00298419, 0.00308135, 0.00160217]), 'mean_score_time': array([0.00401487, 0.00272331, 0.00612435, 0.00356855, 0.00348577,
       0.00456309, 0.00539575, 0.00303583]), 'std_score_time': array([0.00242965, 0.00232325, 0.00593189, 0.00096194, 0.00374822,
       0.00383594, 0.00610481, 0.00198008]), 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
             mask=[False, False, False, False, False, False, False, False],
       fill_value=999999), 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                   'rbf', 'linear'],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'C': 1, 'kernel': 'rbf'}, {'C': 1, 'kernel': 'linear'}, {'C': 10, 'kernel': 'rbf'}, {'C': 10, 'kernel': 'linear'}, {'C': 20, 'kernel': 'rbf'}, {'C': 20, 'kernel': 'linear'}, {'C': 30, 'kernel': 'rbf'}, {'C': 30, 'kernel': 'linear'}], 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
       1.        , 0.96666667, 1.        ]), 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]), 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
       0.9       , 0.9       , 0.9       ]), 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
       0.93333333, 0.93333333, 0.9       ]), 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]), 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
       0.96666667, 0.96      , 0.96      ]), 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
       0.0421637 , 0.03887301, 0.04898979]), 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7])}

In [30]:
results=pd.DataFrame(classifier.cv_results_)

In [31]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.009870,0.003030,0.004015,0.002430,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.009981,0.004546,0.002723,0.002323,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002124,0.001790,0.006124,0.005932,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.005368,0.000409,0.003569,0.000962,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.006863,0.004129,0.003486,0.003748,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.005348,0.002984,0.004563,0.003836,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.003671,0.003081,0.005396,0.006105,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.006010,0.001602,0.003036,0.001980,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [32]:
results[["param_C","param_kernel","mean_test_score"]]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [33]:
# now we use the grid search cv with KNN  model

In [35]:
classifier_2 = GridSearchCV((model_knn),{
    "n_neighbors":[3,5,9,13],
    "weights":["uniform", "distance"],
    "algorithm":["auto","ball_tree","kd_tree","brute"]
},cv=5,return_train_score=False)

In [36]:
classifier_2.fit(x,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=13),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [3, 5, 9, 13],
                         'weights': ['uniform', 'distance']})

In [40]:
print(classifier_2.cv_results_)

{'mean_fit_time': array([0.00750265, 0.00187683, 0.        , 0.00457416, 0.00040355,
       0.00176244, 0.00396714, 0.00563946, 0.00921001, 0.00224457,
       0.00319223, 0.00827761, 0.00283923, 0.00040336, 0.00549927,
       0.00207419, 0.00271349, 0.00319252, 0.00367761, 0.00538402,
       0.00151095, 0.00580578, 0.00160642, 0.00211201, 0.00163026,
       0.00367188, 0.00475965, 0.00304012, 0.00142393, 0.00400243,
       0.0016171 , 0.0033143 ]), 'std_fit_time': array([0.0016839 , 0.00240415, 0.        , 0.00431505, 0.00080709,
       0.00144889, 0.00429856, 0.00643509, 0.0099402 , 0.00163918,
       0.00303258, 0.0071224 , 0.00495543, 0.00080671, 0.00550763,
       0.00199188, 0.00542698, 0.00638504, 0.00550277, 0.00291068,
       0.00187303, 0.00428207, 0.00196748, 0.00422401, 0.00238102,
       0.00290648, 0.00467166, 0.00289574, 0.00199984, 0.0039099 ,
       0.00151136, 0.00285534]), 'mean_score_time': array([0.01662769, 0.00490479, 0.01405382, 0.00471048, 0.00969071,
       0.00463886, 0.00870562, 0.00161262, 0.00835953, 0.00388465,
       0.00913825, 0.        , 0.01060195, 0.00738907, 0.00713696,
       0.00425539, 0.00949807, 0.00769949, 0.00788679, 0.00402575,
       0.01331072, 0.00288796, 0.00799661, 0.0048594 , 0.14774294,
       0.01845613, 0.01864038, 0.01951251, 0.02227569, 0.02057743,
       0.01916828, 0.0203392 ]), 'std_score_time': array([0.00427314, 0.00401376, 0.0029512 , 0.00474375, 0.00554918,
       0.00264998, 0.00901499, 0.00197504, 0.00709387, 0.00259329,
       0.00553673, 0.        , 0.0062676 , 0.00722979, 0.00726294,
       0.00413036, 0.00775559, 0.00705739, 0.00508889, 0.00217531,
       0.00525589, 0.00244074, 0.00499306, 0.00604959, 0.24482772,
       0.00477051, 0.00364593, 0.00690968, 0.00862704, 0.00301247,
       0.00487351, 0.00772358]), 'param_algorithm': masked_array(data=['auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                   'auto', 'ball_tree', 'ball_tree', 'ball_tree',
                   'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                   'ball_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                   'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                   'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                   'brute', 'brute'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_n_neighbors': masked_array(data=[3, 3, 5, 5, 9, 9, 13, 13, 3, 3, 5, 5, 9, 9, 13, 13, 3,
                   3, 5, 5, 9, 9, 13, 13, 3, 3, 5, 5, 9, 9, 13, 13],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=999999), 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                   'uniform', 'distance', 'uniform', 'distance',
                   'uniform', 'distance', 'uniform', 'distance',
                   'uniform', 'distance', 'uniform', 'distance',
                   'uniform', 'distance', 'uniform', 'distance',
                   'uniform', 'distance', 'uniform', 'distance',
                   'uniform', 'distance', 'uniform', 'distance',
                   'uniform', 'distance', 'uniform', 'distance'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'algorithm': 'auto', 'n_neighbors': 3, 'weights': 'uniform'}, {'algorithm': 'auto', 'n_neighbors': 3, 'weights': 'distance'}, {'algorithm': 'auto', 'n_neighbors': 5, 'weights': 'uniform'}, {'algorithm': 'auto', 'n_neighbors': 5, 'weights': 'distance'}, {'algorithm': 'auto', 'n_neighbors': 9, 'weights': 'uniform'}, {'algorithm': 'auto', 'n_neighbors': 9, 'weights': 'distance'}, {'algorithm': 'auto', 'n_neighbors': 13, 'weights': 'uniform'}, {'algorithm': 'auto', 'n_neighbors': 13, 'weights': 'distance'}, {'algorithm': 'ball_tree', 'n_neighbors': 3, 'weights': 'uniform'}, {'algorithm': 'ball_tree', 'n_neighbors': 3, 'weights': 'distance'}, {'algorithm': 'ball_tree', 'n_neighbors': 5, 'weights': 'uniform'}, {'algorithm': 'ball_tree', 'n_neighbors': 5, 'weights': 'distance'}, {'algorithm': 'ball_tree', 'n_neighbors': 9, 'weights': 'uniform'}, {'algorithm': 'ball_tree', 'n_neighbors': 9, 'weights': 'distance'}, {'algorithm': 'ball_tree', 'n_neighbors': 13, 'weights': 'uniform'}, {'algorithm': 'ball_tree', 'n_neighbors': 13, 'weights': 'distance'}, {'algorithm': 'kd_tree', 'n_neighbors': 3, 'weights': 'uniform'}, {'algorithm': 'kd_tree', 'n_neighbors': 3, 'weights': 'distance'}, {'algorithm': 'kd_tree', 'n_neighbors': 5, 'weights': 'uniform'}, {'algorithm': 'kd_tree', 'n_neighbors': 5, 'weights': 'distance'}, {'algorithm': 'kd_tree', 'n_neighbors': 9, 'weights': 'uniform'}, {'algorithm': 'kd_tree', 'n_neighbors': 9, 'weights': 'distance'}, {'algorithm': 'kd_tree', 'n_neighbors': 13, 'weights': 'uniform'}, {'algorithm': 'kd_tree', 'n_neighbors': 13, 'weights': 'distance'}, {'algorithm': 'brute', 'n_neighbors': 3, 'weights': 'uniform'}, {'algorithm': 'brute', 'n_neighbors': 3, 'weights': 'distance'}, {'algorithm': 'brute', 'n_neighbors': 5, 'weights': 'uniform'}, {'algorithm': 'brute', 'n_neighbors': 5, 'weights': 'distance'}, {'algorithm': 'brute', 'n_neighbors': 9, 'weights': 'uniform'}, {'algorithm': 'brute', 'n_neighbors': 9, 'weights': 'distance'}, {'algorithm': 'brute', 'n_neighbors': 13, 'weights': 'uniform'}, {'algorithm': 'brute', 'n_neighbors': 13, 'weights': 'distance'}], 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
       0.96666667, 0.93333333, 0.96666667, 0.96666667, 0.96666667,
       0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
       0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
       0.96666667, 0.96666667, 0.93333333, 0.96666667, 0.96666667,
       0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
       0.93333333, 0.96666667]), 'split1_test_score': array([0.96666667, 0.96666667, 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.96666667, 0.96666667,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 0.96666667, 0.96666667, 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 0.96666667,
       0.96666667, 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        ]), 'split2_test_score': array([0.93333333, 0.93333333, 0.93333333, 0.9       , 0.96666667,
       0.93333333, 0.96666667, 0.96666667, 0.93333333, 0.93333333,
       0.93333333, 0.9       , 0.96666667, 0.93333333, 0.96666667,
       0.96666667, 0.93333333, 0.93333333, 0.93333333, 0.9       ,
       0.96666667, 0.93333333, 0.96666667, 0.96666667, 0.93333333,
       0.93333333, 0.93333333, 0.9       , 0.96666667, 0.93333333,
       0.96666667, 0.96666667]), 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
       0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
       0.96666667, 0.96666667, 0.93333333, 0.96666667, 0.96666667,
       0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
       0.93333333, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
       0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
       0.96666667, 0.96666667]), 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), 'mean_test_score': array([0.96666667, 0.96666667, 0.97333333, 0.96666667, 0.97333333,
       0.97333333, 0.97333333, 0.98      , 0.96666667, 0.96666667,
       0.97333333, 0.96666667, 0.97333333, 0.97333333, 0.97333333,
       0.98      , 0.96666667, 0.96666667, 0.97333333, 0.96666667,
       0.97333333, 0.97333333, 0.97333333, 0.98      , 0.96666667,
       0.96666667, 0.97333333, 0.96666667, 0.98      , 0.97333333,
       0.97333333, 0.98      ]), 'std_test_score': array([0.02108185, 0.02108185, 0.02494438, 0.03651484, 0.02494438,
       0.02494438, 0.02494438, 0.01632993, 0.02108185, 0.02108185,
       0.02494438, 0.03651484, 0.02494438, 0.02494438, 0.02494438,
       0.01632993, 0.02108185, 0.02108185, 0.02494438, 0.03651484,
       0.02494438, 0.02494438, 0.02494438, 0.01632993, 0.02108185,
       0.02108185, 0.02494438, 0.03651484, 0.01632993, 0.02494438,
       0.02494438, 0.01632993]), 'rank_test_score': array([21, 21,  6, 21,  6,  6,  6,  1, 21, 21,  6, 21,  6,  6,  6,  1, 21,
       21,  6, 21,  6,  6,  6,  1, 21, 21,  6, 21,  1,  6,  6,  1])}

In [41]:
results=pd.DataFrame(classifier_2.cv_results_)

In [42]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.007503,0.001684,0.016628,0.004273,auto,3,uniform,"{'algorithm': 'auto', 'n_neighbors': 3, 'weigh...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,21
1,0.001877,0.002404,0.004905,0.004014,auto,3,distance,"{'algorithm': 'auto', 'n_neighbors': 3, 'weigh...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,21
2,0.000000,0.000000,0.014054,0.002951,auto,5,uniform,"{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,6
3,0.004574,0.004315,0.004710,0.004744,auto,5,distance,"{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,21
4,0.000404,0.000807,0.009691,0.005549,auto,9,uniform,"{'algorithm': 'auto', 'n_neighbors': 9, 'weigh...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,6
5,0.001762,0.001449,0.004639,0.002650,auto,9,distance,"{'algorithm': 'auto', 'n_neighbors': 9, 'weigh...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,6
6,0.003967,0.004299,0.008706,0.009015,auto,13,uniform,"{'algorithm': 'auto', 'n_neighbors': 13, 'weig...",0.933333,1.000000,0.966667,0.966667,1.0,0.973333,0.024944,6
7,0.005639,0.006435,0.001613,0.001975,auto,13,distance,"{'algorithm': 'auto', 'n_neighbors': 13, 'weig...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
8,0.009210,0.009940,0.008360,0.007094,ball_tree,3,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 3, '...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,21
9,0.002245,0.001639,0.003885,0.002593,ball_tree,3,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 3, '...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,21
10,0.003192,0.003033,0.009138,0.005537,ball_tree,5,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 5, '...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,6
11,0.008278,0.007122,0.000000,0.000000,ball_tree,5,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 5, '...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,21
12,0.002839,0.004955,0.010602,0.006268,ball_tree,9,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 9, '...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,6
13,0.000403,0.000807,0.007389,0.007230,ball_tree,9,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 9, '...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,6
14,0.005499,0.005508,0.007137,0.007263,ball_tree,13,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 13, ...",0.933333,1.000000,0.966667,0.966667,1.0,0.973333,0.024944,6
15,0.002074,0.001992,0.004255,0.004130,ball_tree,13,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 13, ...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
16,0.002713,0.005427,0.009498,0.007756,kd_tree,3,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 3, 'we...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,21
17,0.003193,0.006385,0.007699,0.007057,kd_tree,3,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 3, 'we...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,21
18,0.003678,0.005503,0.007887,0.005089,kd_tree,5,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 5, 'we...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,6
19,0.005384,0.002911,0.004026,0.002175,kd_tree,5,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 5, 'we...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,21
20,0.001511,0.001873,0.013311,0.005256,kd_tree,9,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 9, 'we...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,6
21,0.005806,0.004282,0.002888,0.002441,kd_tree,9,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 9, 'we...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,6
22,0.001606,0.001967,0.007997,0.004993,kd_tree,13,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 13, 'w...",0.933333,1.000000,0.966667,0.966667,1.0,0.973333,0.024944,6
23,0.002112,0.004224,0.004859,0.006050,kd_tree,13,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 13, 'w...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
24,0.001630,0.002381,0.147743,0.244828,brute,3,uniform,"{'algorithm': 'brute', 'n_neighbors': 3, 'weig...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,21
25,0.003672,0.002906,0.018456,0.004771,brute,3,distance,"{'algorithm': 'brute', 'n_neighbors': 3, 'weig...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,21
26,0.004760,0.004672,0.018640,0.003646,brute,5,uniform,"{'algorithm': 'brute', 'n_neighbors': 5, 'weig...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,6
27,0.003040,0.002896,0.019513,0.006910,brute,5,distance,"{'algorithm': 'brute', 'n_neighbors': 5, 'weig...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,21
28,0.001424,0.002000,0.022276,0.008627,brute,9,uniform,"{'algorithm': 'brute', 'n_neighbors': 9, 'weig...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
29,0.004002,0.003910,0.020577,0.003012,brute,9,distance,"{'algorithm': 'brute', 'n_neighbors': 9, 'weig...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,6
30,0.001617,0.001511,0.019168,0.004874,brute,13,uniform,"{'algorithm': 'brute', 'n_neighbors': 13, 'wei...",0.933333,1.000000,0.966667,0.966667,1.0,0.973333,0.024944,6
31,0.003314,0.002855,0.020339,0.007724,brute,13,distance,"{'algorithm': 'brute', 'n_neighbors': 13, 'wei...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1

In [44]:
results[["param_algorithm","param_n_neighbors","param_weights","mean_test_score"]]

   param_algorithm  param_n_neighbors param_weights  mean_test_score
0             auto                  3       uniform         0.966667
1             auto                  3      distance         0.966667
2             auto                  5       uniform         0.973333
3             auto                  5      distance         0.966667
4             auto                  9       uniform         0.973333
5             auto                  9      distance         0.973333
6             auto                 13       uniform         0.973333
7             auto                 13      distance         0.980000
8        ball_tree                  3       uniform         0.966667
9        ball_tree                  3      distance         0.966667
10       ball_tree                  5       uniform         0.973333
11       ball_tree                  5      distance         0.966667
12       ball_tree                  9       uniform         0.973333
13       ball_tree                  9      distance         0.973333
14       ball_tree                 13       uniform         0.973333
15       ball_tree                 13      distance         0.980000
16         kd_tree                  3       uniform         0.966667
17         kd_tree                  3      distance         0.966667
18         kd_tree                  5       uniform         0.973333
19         kd_tree                  5      distance         0.966667
20         kd_tree                  9       uniform         0.973333
21         kd_tree                  9      distance         0.973333
22         kd_tree                 13       uniform         0.973333
23         kd_tree                 13      distance         0.980000
24           brute                  3       uniform         0.966667
25           brute                  3      distance         0.966667
26           brute                  5       uniform         0.973333
27           brute                  5      distance         0.966667
28           brute                  9       uniform         0.980000
29           brute                  9      distance         0.973333
30           brute                 13       uniform         0.973333
31           brute                 13      distance         0.980000